/**
 * app/api/flw-verify/route.ts
 *
 * GET /api/flw-verify?transaction_id=<flw_id>&tx_ref=<our_ref>&status=<successful|failed>
 *
 * Flutterwave appends these three params to redirect_url automatically.
 * We always re-verify server-side — never trust the client status param alone.
 *
 * Note: `tx_ref` here IS your `reference` column value (it's what was
 * generated by generateReference() and passed as tx_ref at checkout) —
 * updateOrderStatus looks it up by `reference`, not `flutterwave_tx_ref`.
 */
import { NextRequest, NextResponse } from "next/server"
import { verifyFlutterwaveTransaction } from "@/lib/flutterwave"
import { updateOrderStatus } from "@/lib/orders-admin"

export async function GET(req: NextRequest) {
  const { searchParams } = req.nextUrl
  const transactionId = searchParams.get("transaction_id")
  const txRef         = searchParams.get("tx_ref")   // == your `reference` column
  const clientStatus  = searchParams.get("status")

  if (!transactionId || !txRef) {
    return NextResponse.json({ error: "Missing transaction params" }, { status: 400 })
  }

  if (clientStatus === "cancelled") {
    await updateOrderStatus(txRef, "failed").catch(console.error)
    return NextResponse.json({ status: "cancelled", tx_ref: txRef })
  }

  try {
    const tx = await verifyFlutterwaveTransaction(transactionId)

    if (tx.status === "successful") {
      // DB status uses "completed" (matches the orders_status_check
      // constraint). flw_ref/transactionId are recorded as confirmation
      // metadata on top of the reference match — not the lookup key itself.
      await updateOrderStatus(tx.tx_ref, "completed", {
        txRef: tx.flw_ref,
        transactionId,
      })
      return NextResponse.json({ status: "paid", tx_ref: tx.tx_ref, amount_naira: tx.amount })
    } else {
      await updateOrderStatus(tx.tx_ref, "failed")
      return NextResponse.json({ status: tx.status, tx_ref: tx.tx_ref })
    }
  } catch (err: any) {
    console.error("[flw-verify]", err)
    return NextResponse.json({ error: err.message }, { status: 500 })
  }
}