import "server-only"
import { supabaseAdmin } from "@/lib/supabase-admin"
import type { CartItem } from "@/types/Product"

// SERVER-ONLY writes to `orders`. Never import from a "use client" file.
//
// IMPORTANT: `reference` (generated by generateReference() in
// lib/flutterwave.ts, e.g. "SS-XXXX-XXXX") is the actual lookup key used
// throughout checkout/verify — it's what gets passed to Flutterwave as
// `tx_ref` and comes back in the redirect params. `flutterwave_tx_ref` and
// `flutterwave_transaction_id` are separate metadata columns, filled in
// AFTER verification with Flutterwave's own identifiers — they are not
// what you look orders up by.

interface OrderItemInput {
  id:            string
  name:          string
  image_url:     string
  price:         number
  quantity:      number
  selectedSize:  string
  selectedColor: string
}

interface CreateOrderInput {
  reference:     string
  email:         string
  customerName:  string
  phone?:        string
  address:       string
  city:          string
  state:         string
  cart:          CartItem[]
  deliveryFee?:  number    // defaults to 0 — Paystack checkout doesn't add one
  userId?:       string | null   // defaults to null (guest checkout)
}

export interface CreateOrderResult {
  reference: string
  amount:    number   // subtotal + delivery, server-verified
}

/**
 * Creates a "pending" order.
 *
 * SECURITY-CRITICAL: item prices are re-fetched from the `products` table
 * here rather than trusting `cart[].price` from the client — the previous
 * version of this route summed client-sent prices directly, which meant
 * anyone could tamper with the request body to pay less than the real
 * total. `deliveryFee` is still taken as given, since it's a flat rate
 * rather than something tied to product pricing — let me know if delivery
 * pricing should also be validated against a known rate table.
 */
export async function createOrder({
  reference, email, customerName, phone, address, city, state,
  cart, deliveryFee = 0, userId = null,
}: CreateOrderInput): Promise<CreateOrderResult> {
  const productIds = cart.map((item) => item.id)

  const { data: products, error: productsError } = await supabaseAdmin
    .from("products")
    .select("id, name, price, image_url")
    .in("id", productIds)

  if (productsError) throw productsError

  const productMap = new Map(products.map((p) => [p.id, p]))

  let subtotal = 0
  const items: OrderItemInput[] = cart.map((cartItem) => {
    const product = productMap.get(cartItem.id)
    if (!product) {
      throw new Error(`Product ${cartItem.id} no longer exists — remove it from your cart.`)
    }
    const price = Number(product.price)   // server-verified, not client-sent
    subtotal += price * cartItem.quantity
    return {
      id:            product.id,
      name:          product.name,
      image_url:     product.image_url,
      price,
      quantity:      cartItem.quantity,
      selectedSize:  cartItem.selectedSize,
      selectedColor: cartItem.selectedColor,
    }
  })

  const amount = subtotal + deliveryFee

  const { error: insertError } = await supabaseAdmin
    .from("orders")
    .insert({
      reference,
      status: "pending",
      email,
      customer_name: customerName,
      phone,
      address,
      city,
      state,
      items,
      amount_naira: amount,
      amount,                          // kept in sync, matching your original design
      user_id: userId,
      flutterwave_tx_ref: null,
      flutterwave_transaction_id: null,
    })

  if (insertError) throw insertError

  return { reference, amount }
}

/**
 * Updates an order's status by matching its `reference` — NOT
 * `flutterwave_tx_ref` (that was the bug). Call this only after
 * independently verifying the transaction with Flutterwave/Paystack's own
 * API. Optionally records Flutterwave's own transaction identifiers once
 * verification succeeds.
 */
export async function updateOrderStatus(
  reference: string,
  status: string,
  flutterwaveMeta?: { txRef?: string; transactionId?: string }
) {
  const { data, error } = await supabaseAdmin
    .from("orders")
    .update({
      status,
      ...(flutterwaveMeta?.txRef        ? { flutterwave_tx_ref: flutterwaveMeta.txRef } : {}),
      ...(flutterwaveMeta?.transactionId ? { flutterwave_transaction_id: flutterwaveMeta.transactionId } : {}),
    })
    .eq("reference", reference)
    .select()
    .single()

  if (error) throw error
  return data
}